### ISSUE TITLE
Add `operator~` for enums

### ISSUE THREAD

**Issue by DethRaid** [spnda/fastgltf#12]
`fastgltf` has a number of enums that can be `or`'d together, like `fastgltf::Category` or `fastgltf::Options`. These enums should support the bit-inverse operator `~`, and any other bitwise operators

**Comment by spnda** [comment]
Somewhat already fixed by e9200a921713267fcd298e99304d20ef3331c2e8, but I think e9200a921713267fcd298e99304d20ef3331c2e8 fully fixes this.
