### ISSUE TITLE
fastgltf probably shouldn't use tellg to get file sizes, might not always be the file size

### ISSUE THREAD

**Issue by EvilTrev** [spnda/fastgltf#17]
Seen here for example:
```
    std::ifstream file(path, std::ios::ate | std::ios::binary);
    auto length = static_cast<std::streamsize>(file.tellg());
    file.seekg(0);
```

This has some issues, and there is a bunch of discussion here: https://stackoverflow.com/questions/2409504/using-c-filestreams-fstream-how-can-you-determine-the-size-of-a-file

But long, short, if using c++17 or later, then:

```
   auto length = std::filesystem::file_size( path );
```

**Comment by spnda** [comment]
I am aware of this issue and I do use [this answer](https://stackoverflow.com/a/2409538)'s idea in the [GltfDataBuffer](https://github.com/spnda/fastgltf/blob/2524685d7178df6125df003f34e8edeb45b88bcd/src/fastgltf.cpp#L2369-2372). Could you please pinpoint a line where I do use tellg?
