### ISSUE TITLE
Integration issues with the downloaded simdjson when using find_package()

### ISSUE THREAD

**Issue by Bonkt** [spnda/fastgltf#35]
Im trying to build this library and use it in my project with find_package(), but get the following CMake error:
I'm on ubuntu and generally find_package() works fine for most libraries im trying to build, but i'm not an cmake expert. I can't really find what im doing wrong or missing, and my skills is lacking when trying to trace back through the internal CMakeLists.txt.

How i installed the library: (with simdjson downloaded = ON)
1. mkdir build; cd build;
2. cmake..
3. make
4. sudo make install
Am i missing any steps? CMake obviously finds the fastgltfConfig file, but there are problems with the simdjson installation.
When building my own project with this library i get:
```
CMake Error at CMakeLists.txt:71 (find_package):
  Found package configuration file:

 /usr/local/lib/cmake/fastgltf/fastgltfConfig.cmake

  but it set fastgltf_FOUND to FALSE so package "fastgltf" is considered to
  be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  fastgltf::fastgltf_simdjson
````

Output when running _make install_:
```
Consolidate compiler generated dependencies of target fastgltf_simdjson
[ 40%] Built target fastgltf_simdjson
Consolidate compiler generated dependencies of target fastgltf
[100%] Built target fastgltf
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/include/simdjson.h
-- Installing: /usr/local/lib/libfastgltf_simdjson.a
-- Installing: /usr/local/lib/cmake/fastgltf/fastgltf_simdjsonTargets.cmake
-- Installing: /usr/local/lib/cmake/fastgltf/fastgltf_simdjsonTargets-noconfig.cmake
-- Up-to-date: /usr/local/include/fastgltf/base64.hpp
-- Up-to-date: /usr/local/include/fastgltf/glm_element_traits.hpp
-- Up-to-date: /usr/local/include/fastgltf/parser.hpp
-- Up-to-date: /usr/local/include/fastgltf/tools.hpp
-- Up-to-date: /usr/local/include/fastgltf/types.hpp
-- Up-to-date: /usr/local/include/fastgltf/util.hpp
-- Installing: /usr/local/lib/libfastgltf.a
-- Old export file "/usr/local/lib/cmake/fastgltf/fastgltfConfig.cmake" will be replaced.  Removing files [/usr/local/lib/cmake/fastgltf/fastgltfConfig-noconfig.cmake].
-- Installing: /usr/local/lib/cmake/fastgltf/fastgltfConfig.cmake
-- Installing: /usr/local/lib/cmake/fastgltf/fastgltfConfig-noconfig.cmake
```

**Comment by TareHimself** [comment]
Did u find another solution ?

**Comment by spnda** [comment]
@TareHimself I noticed you put a commit on your fork of fastgltf. Does that fix work generally with the subfolder for simdjson? (`share/fastgltf/simdjson`). I thought there had to be a dedicated folder, which is why I was reluctant because I might overwrite simdjson's own installation targets. If it does work, would you mind if I cherry-pick that commit onto my repository?

**Comment by TareHimself** [comment]
Yes it does , I can open a pr

**Comment by TareHimself** [comment]
I have simdjson in its own folder under fastgltf so its cmake/fastgltf/simdjson . I have no clue if it will work if I put both of them in the same folder

**Comment by spnda** [comment]
I only just tested this locally on my Mac and `find_package(fastgltf CONFIG REQUIRED)` still fails when the simdjson configs are in a subdirectory. Are you *sure* it works, and on what platform are you with which CMake version?

**Comment by TareHimself** [comment]
If I do not do `find_package(fastgltf_simdjson REQUIRED)` it fails

**Comment by TareHimself** [comment]
I am on cmake 3.28.1

**Comment by TareHimself** [comment]
Just updated the fork so it finds simdjson by itself, not sure if this works for a user_provided simdjson tho

**Comment by spnda** [comment]
Instead of using `find_dependency(fastgltf_simdjson REQUIRED)`, which brings up the same issue as we originally had, we can just include the `fastgltf_simdjsonConfig.cmake` from the same install directory, which seems to completely fix the issue for me. Can you verify this on your end? I'll merge it then and fix some style issues with it afterwards.

**Comment by TareHimself** [comment]
But how would that work if it was not installed with fastgltf_simdjson ?

**Comment by spnda** [comment]
As I said, it's the same error as before. It won't look into the local or the `cmake/fastgltf` directory for files for the `fastgltf_simdjson` target.

Perhaps I should just link simdjson.cpp and simdjson.directly into the fastgltf target... That would probably be easier than this fighting with CMake.
