### ISSUE TITLE
Exporting as glb with embedded buffer does not work for fastgltf::sources::ByteView

### ISSUE THREAD

**Issue by Cyphall** [spnda/fastgltf#48]
Seems to be caused by the `sources::ByteView` case missing the if statement present in `sources::Array` and `sources::Vector`: https://github.com/spnda/fastgltf/blob/f8ed5a09e761dab002c143735c3643323435fac4/src/fastgltf.cpp#L4189-L4211

**Comment by Cyphall** [comment]
When exporting as glb an asset with one buffer (small or large, doesn't matter) whose data field is an `fastgltf::sources::ByteView`, the buffer is created in a separate file instead of being embedded in the glb file

**Comment by spnda** [comment]
Okay, so what I thought. That is fixed now in the latest commit. Thanks again for reporting.
