### ISSUE TITLE
BUG: KHR_materials_anisotropy not functioning (material.anisotropy pointer not assigned)

### ISSUE THREAD

**Issue by droettger** [spnda/fastgltf#58]
Bug: KHR_materials_anisotropy extension handling is missing `material.anisotropy = std::move(anisotropy);` before this line:
https://github.com/spnda/fastgltf/blob/main/src/fastgltf.cpp#L2480

**Comment by spnda** [comment]
Thank you for reporting. Sorry about this... I should write more tests covering all the extensions properly.
