### ISSUE TITLE
Add option to disable modules even if support is detected

### ISSUE THREAD

**Issue by MCredstoner2004** [spnda/fastgltf#62]
I am working on a project that uses CMake as it's build system  want to use this project as a submodule and  just add_subdirectory it, however, fastgltf is (correctly) detecting compiler support for C++ modules, but CMake only supports using modules with a limited number of generators, and I'd like my project to be buildable by Unix Makefiles

**Comment by spnda** [comment]
Does it just error out since CMake detects that you're using Makefiles? Or does the error happen during build? If it's during configuring I could change the detect method to check what generator is being used, too.

**Comment by MCredstoner2004** [comment]
> Does it just error out since CMake detects that you're using Makefiles? Or does the error happen during build? If it's during configuring I could change the detect method to check what generator is being used, too.

I just checked by setting `FASTGLTF_SUPPORTS_MODULES` to false and it does build properly, so just checking that the generator used is one of the listed in [the documentation](https://cmake.org/cmake/help/latest/manual/cmake-cxxmodules.7.html#generator-support) should work

**Comment by spnda** [comment]
There is no way to detect the version of the used generator, so I've just settled with using an extra option that enables/disables the module target. Thanks for the report.
