### ISSUE TITLE
Crash when trying to assign a new asset to an existing asset

### ISSUE THREAD

**Issue by droettger** [spnda/fastgltf#65]
**1.) BUG**
Crash when trying to assign an asset to an existing asset (while implementing drag-and-drop of glTF files.)
The problem seems to be the order in which things are moved. 
Given the comment about the importance of the order of the memoryResource field here:
```
#if !FASTGLTF_DISABLE_CUSTOM_MEMORY_POOL
		// This has to be first in this struct so that it gets destroyed last, leaving all allocations
		// alive until the end.
		std::shared_ptr<ChunkMemoryResource> memoryResource;
#endif
```
I tried changing the order of operations inside the Asset move operators and things work when the memoryResource is moved last(!) like this:
```
        Asset(Asset&& other) noexcept :
				assetInfo(std::move(other.assetInfo)),
				extensionsUsed(std::move(other.extensionsUsed)),
				extensionsRequired(std::move(other.extensionsRequired)),
				defaultScene(other.defaultScene),
				accessors(std::move(other.accessors)),
				animations(std::move(other.animations)),
				buffers(std::move(other.buffers)),
				bufferViews(std::move(other.bufferViews)),
				cameras(std::move(other.cameras)),
				images(std::move(other.images)),
				lights(std::move(other.lights)),
				materials(std::move(other.materials)),
				meshes(std::move(other.meshes)),
				nodes(std::move(other.nodes)),
				samplers(std::move(other.samplers)),
				scenes(std::move(other.scenes)),
				skins(std::move(other.skins)),
				textures(std::move(other.textures)),
				materialVariants(std::move(other.materialVariants)),
				availableCategories(other.availableCategories)
#if !FASTGLTF_DISABLE_CUSTOM_MEMORY_POOL
				, memoryResource(std::move(other.memoryResource)) // FIX assigning assets works when this happens last.
#endif
        {}

		Asset& operator=(const Asset& other) = delete;
		Asset& operator=(Asset&& other) noexcept {
			assetInfo = std::move(other.assetInfo);
			extensionsUsed = std::move(other.extensionsUsed);
			extensionsRequired = std::move(other.extensionsRequired);
			defaultScene = other.defaultScene;
			accessors = std::move(other.accessors);
			animations = std::move(other.animations);
			buffers = std::move(other.buffers);
			bufferViews = std::move(other.bufferViews);
			cameras = std::move(other.cameras);
			images = std::move(other.images);
			lights = std::move(other.lights);
			materials = std::move(other.materials);
			meshes = std::move(other.meshes);
			nodes = std::move(other.nodes);
			samplers = std::move(other.samplers);
			scenes = std::move(other.scenes);
			skins = std::move(other.skins);
			textures = std::move(other.textures);
			materialVariants = std::move(other.materialVariants);
			availableCategories = other.availableCategories;
#if !FASTGLTF_DISABLE_CUSTOM_MEMORY_POOL
			memoryResource = std::move(other.memoryResource); // FIX assigning assets works when this happens last.
#endif
			return *this;
		}
```
**2.) BUG**
Trying to isolate it by disabling `FASTGLTF_DISABLE_CUSTOM_MEMORY_POOL` inside the CMake GUI didn't work at all.
That crashed in parseAccessors() with uninitialized data, accessor.size() is huge.
(Using KhronosGroup glTF-Sample-Assets BoomBox.gltf.)
```
fg::Error fg::Parser::parseAccessors(simdjson::dom::array& accessors, Asset& asset) {
    using namespace simdjson;

    asset.accessors.reserve(accessors.size()); // BUG This is huge. Works with FASTGLTF_DISABLE_CUSTOM_MEMORY_POOL enabled.
...
I didn't look into that further.

**Comment by spnda** [comment]
I can't reproduce the second bug you're reporting. Loading BoomBox.gltf `accessors.size()` is returning `5` for me, regardless of `FASTGLTF_DISABLE_CUSTOM_MEMORY_POOL`.

**Comment by droettger** [comment]
I would need to check in the second problem again. I just set the flag inside the CMake 3.29.5 GUI and rebuilt all (debug only).
I'm under Windows 10, MSVS 2022 update 17.10.3 with MSC 19.40 since yesterday.

What accessor tools do you mean?
If this is about the tedious conversion routines inside that examples that's because CUDA has different memory alignment restrictions than OpenGL and I cannot handle the existing data via the Accessor->BufferView->Buffer formats directly. That's what the simpler OptiX SDK examples try and fail miserably. Or I would need to read everything as scalars which would be even worse. Then OptiX has some more restrictions on the supported input data like no uchar indices.

I'm not on top-of-tree of fastgltf inside that example source on purpose.
I only update fastgltf internaly when I hit an error, like today and that requires adjustment to your API changes every time.
If you really want to make me happy, change all tabs against spaces inside the code to get consistent formatting in any editor. :-)

**Comment by spnda** [comment]
I was on 17.10.2 earlier, and upgraded to 17.10.3, and still got the same good result with the OpenGL example.

> What accessor tools do you mean?

fastgltf has a header containing deserialization functions for accessor data, so that you can copy it into your buffers directly (with respect to a certain stride, too), or you can just use a function to iterate over the data. The functions take care of sparse accessors and data alignment (incl. the weird matrix cases) for you, and can also convert from any generic type to whatever you need (to support KHR_mesh_quantization transparently). I looked into the OptiX_Apps code and was just surprised to see that you essentially redid the whole deserialization logic for accessors (albeit correctly, which surprised me, too, since most people get it wrong). I was wondering if there's any reason to avoid them, or if you didn't know they existed. I have a page about them in the documentation: https://fastgltf.readthedocs.io/latest/tools.html

I was originally going to contribute to the repository myself to use the accessor tools instead, but could never get the build working.

> If you really want to make me happy, change all tabs against spaces inside the code to get consistent formatting in any editor.

I wanted to switch slowly over time, with every modification converting the touched code to tabs, since I wanted to avoid a commit that changed 10.000+ lines of code. Now that most of the code has been converted, I might make the proper switch sometime soon. I also didn't want to use an automatic converter, since I know that CLion's converter messes up a few things.

**Comment by droettger** [comment]
>I looked into the OptiX_Apps code and was just surprised to see that you essentially redid the whole deserialization logic for accessors (albeit correctly, which surprised me, too, since most people get it wrong).

Yeah, because I'm a professional. ;-) Seriously, I'm a former OpenGL driver engineer and know how to read Khronos specs.

Right, the original example inside the OptiX SDK I started from was using the tinygltf library and I switched to fastgltf when I couldn't figure out how to get extensions on extensions working in tinygltf, while you were already supporting the extensions out-of-the-box I wanted for a decent material implementation. Nice!
And then I needed to get used to the more modern C++ usage like std::variants and figuring out how to convert glTF's OpenGL centric data management to what CUDA required and what I wanted in my renderer implementation, correcting all the things the original OptiX SDK example botched, so I just did that manually. 
There are too many options and special cases inside glTF already and I'm fine when I know exactly what the code does and I wasn't aware of the Accessor tools.

>I was originally going to contribute to the repository myself to use the accessor tools instead, but could never get the build working.

It should just work when following the instructions inside the **Building** chapter by the letter. 
Agreed, its a little involved, also due some licensing legal reasons. 
After syncing the repository (fastgltf, glm and stb are included as sub-modules) the **3rdparty.cmd** must be run once inside the **x64 Native Tools Command Prompt for VS 2022** to download some other libraries and build assimp and fastgltf. 
You can also just set the `FASTGLTF_PATH` environment variable which is used inside my `FindFastGLTF.cmake` to use any other fastgltf location on disk. 
If you only want to build the GLTF_renderer example, you can comment out all other examples inside the apps/CMakeLists.txt which will get rid of the MDL SDK dependencies.

The official release of the samples should just download working versions of all dependencies. It's good enough when the main branch works. This is all example work, no critical production code.
