### ISSUE TITLE
Add support for Draco compression

### ISSUE THREAD

**Issue by tigrazone** [spnda/fastgltf#66]
Is exists way to read files with draco compression?

**Comment by SirBob01** [comment]
Any updates here? I prefer this library's API over tinygltf. This is the only thing I need that isn't supported yet.

**Comment by edunad** [comment]
Same here, loving the lib so far :D

**Comment by spnda** [comment]
I've added initial support for KHR_draco_mesh_compression. I've only tested it against the BrainStem.gltf on two meshes, but I think this should do it.

This marks the last Khronos extension asides from animation_pointer and that weird XMP extension, which would be hard/impossible to support nicely, I think.
