### ISSUE TITLE
Warnings on clang / macOS

### ISSUE THREAD

**Issue by t0rakka** [spnda/fastgltf#77]
fastgltf.cpp:818:19 Loop variable 'field' binds to a temporary value produced by a range of type 'simdjson::dom::object'
fastgltf.cpp:1502:19 Loop variable 'object' binds to a temporary value produced by a range of type 'simdjson::dom::object'

`
for (const auto& object : root) {
`

Clang (latest, clang-1600.0.26.3) on macOS gives a warning. Iterate by value instead of reference -> no warning. Just a cosmetic issue..

**Comment by spnda** [comment]
> Just a cosmetic issue..

Nope, this is definitely UB. simdjson iterators do not return a reference in their `operator*()` overload, but instead just a `const key_value_pair`. I've fixed it in both locations as you reported, thank you.
