### ISSUE TITLE
C++ 20 support

### ISSUE THREAD

**Issue by preetishkakkar** [spnda/fastgltf#9]
Currently, cmake seems to make sure that we can't use it with a C++ 20 project? Is there a reason to have this restricted to C++ 17, can this limit be removed?

**Comment by spnda** [comment]
fastgltf definitely supports C++20 and even includes a few additional things in the headers, if you should use the utilities it adds. Additionally, CMake should not have any issue with the C++ version of your project and fastgltf. Would you mind pasting the error message you encountered?

**Comment by preetishkakkar** [comment]
sure, I am hitting this when fastgltf.cpp is being compiled (fatal error C1189: #error:  "fastgltf requires C++17"), below line.

#if !defined(__cplusplus) || (!defined(_MSVC_LANG) && __cplusplus < 201703L) || (defined(_MSVC_LANG) && _MSVC_LANG < 201703L)
#error "fastgltf requires C++17"
#endif

**Comment by preetishkakkar** [comment]
ahh never mind, looks like since there was no easy way to compile only parts of fastgltf, I added below to my cmake, 
add_library(fastgltf STATIC ${fastgltf_SOURCE_DIR}/src/base64_decode.cpp ${fastgltf_SOURCE_DIR}/src/fastgltf.cpp ${fastgltf_SOURCE_DIR}/simdjson/simdjson.cpp)

which somehow didn't pick the correct cxx flags set at project level, adding this target_compile_features(fastgltf PRIVATE cxx_std_20) works! thanks.. 

It will be good to have possibility to configuring it such that examples & test can be turned off when using FetchContent_Declare

**Comment by preetishkakkar** [comment]
Feel free to close this issue

**Comment by spnda** [comment]
I will keep it open to remind me about adding a FASTGLTF_TESTS and FASTGLTF_EXAMPLES that fully stops anything regarding tests and examples of running. But thank you.
